### PR TITLE
Remove cupertino dependencies (FormBuilderCupertinoSegmentedControl)

### PR DESCRIPTION
**Pull request by deandreamatias**
## Solution description

Remove all references to cupertino widgets

- Remove `FormBuilderCupertinoSegmentedControl` field
- Update custom fields example without cupertino widgets
- Remove cupertino icons dependency

## To Do

- [x] Read [contributing guide](https://github.com/flutter-form-builder-ecosystem/.github/blob/main/CONTRIBUTING.md)
- [ ] Check the original issue to confirm it is fully satisfied
- [x] Add solution description to help guide reviewers
- [ ] Add unit test to verify new or fixed behaviour
- [x] If apply, add documentation to code properties and package readme

### CODE REVIEW

**Comment by anqit** [comment]
Is there a replacement form field to use instead?

**Comment by deandreamatias** [comment]
> Is there a replacement form field to use instead? I relied on FormBuilderSegmentedControl in a project, and it's omission is preventing me from upgrading

Yes, had @anqit 
https://github.com/flutter-form-builder-ecosystem/form_builder_cupertino_fields

**Comment by anqit** [comment]
> > Is there a replacement form field to use instead? I relied on FormBuilderSegmentedControl in a project, and it's omission is preventing me from upgrading
> 
> Yes, had @anqit https://github.com/flutter-form-builder-ecosystem/form_builder_cupertino_fields

Awesome, thanks! Not sure how I missed that. Just out of curiosity, any reason why it's a Cupertino-specific field, and are there plans to do a material version of it as well?

**Comment by deandreamatias** [comment]
I split to allow create package for each design system. Like Flutter, in main package has the material design fields and Cupertino and others like secondary

**Pull request merged**
