### PR TITLE
Bump version of intl to 0.18.0; Bump version of Flutter to 3.10.0; Bu…

### PR DESCRIPTION
**Pull request by danielroek**
…mp version to 9.0.0.dev.2

## Solution description
Bumps intl to 0.18.0. Requires [form_builder_validators #50](https://github.com/flutter-form-builder-ecosystem/form_builder_validators/pull/50) to be merged. 

## To Do

- [x] Read [contributing guide](https://github.com/flutter-form-builder-ecosystem/.github/blob/main/CONTRIBUTING.md)
- [ ] Check the original issue to confirm it is fully satisfied
- [ ] Add solution description to help guide reviewers
- [ ] Add unit test to verify new or fixed behaviour
- [ ] If apply, add documentation to code properties and package readme

### CODE REVIEW

**Comment by motucraft** [comment]
I ran into this problem when trying to bring my version of Flutter up to date. I appreciate your correspondence.

**Comment by okerivy** [comment]
I also met this problem. How can I solve it?

**Comment by danielroek** [comment]
If you really need to migrate to Dart 3 and Flutter 3.10.0 now, you can add this branch to your pubspec.yaml

Like this:
```yaml
  flutter_form_builder:
    git:
      url: https://github.com/danielroek/flutter_form_builder
```

**Comment by deandreamatias** [comment]
I will update this on main branch

**Pull request closed without merging**
